javac clientconnection/ClientConnection.java
javac clientmessagehandler/ClientMessageHandler.java
javac server/Server.java
javac servertest/ServerTest.java
javac standardiouserinterface/StandardIO.java
javac usercommandhandler/UserCommandHandler.java
javac userinterface/UserInterface.java
