del clientconnection\ClientConnection.class
del clientmessagehandler\ClientMessageHandler.class
del server\Server.class
del servertest\ServerTest.class
del standardiouserinterface\StandardIO.class
del usercommandhandler\UserCommandHandler.class
del userinterface\UserInterface.class
